framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/website/manifest.json'
#        packages:
#            admin:
#                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'