version: '2'
services:
  apache:
    image: cultureweb/symfony:5-php-7.4-v2.0
    volumes:
      - "./docker.php.settings.ini:/usr/local/etc/php/conf.d/docker.php.settings.ini"
      - "./:/var/www/html"
      - "/var/www/html/var"
    links:
      - mysql:mysqlhost
    ports:
      - 8742:80
    environment:
      - DOCKER_DEBUG=1
      - DOCKER_CACHE=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      -  8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  mysql:
    image: mysql:5.7
    volumes:
      - "./_docker-data-mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF
